import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";

const dejavu = LocalFont({
  src: [
    {
      path: "./(fonts)/FiraGO-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dejavu.className} antialiased`}>{children}</body>
    </html>
  );
}
